# Generated by Django 5.0.2 on 2024-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_predictedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null='True')),
                ('phone', models.CharField(max_length=10, null='True')),
                ('desc', models.TextField(null='True')),
            ],
        ),
    ]
