# Generated by Django 5.0.2 on 2025-04-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_predictedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='predictedvideo',
            name='detected_label',
            field=models.CharField(default='Not Detected', max_length=255),
        ),
        migrations.AddField(
            model_name='predictedvideo',
            name='processed_video',
            field=models.FileField(null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='predictedvideo',
            name='uploaded_video',
            field=models.FileField(null=True, upload_to='uploaded_videos/'),
        ),
    ]
