# Generated by Django 5.0.2 on 2025-04-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('detected_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('frame_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
