# Generated by Django 5.0.2 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_cheatingdetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatingdetection',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cheatingdetection',
            name='screenshot',
            field=models.ImageField(null='True', upload_to='detections/'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='cheatingdetection',
            name='detected_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cheatingdetection',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
